name: Django CI 

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r docs/requirements.txt
        pip install -e .
        pip install -r requirements/py3.txt

    - name: Run tests
      run: |
        source venv/bin/activate
        python tests/runtests.py